board/config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  root 'post#index'

  get 'post/post'

  get 'post/edit/:id' => 'post#edit'

  get 'post/update/:id' => 'post#update'

  get 'post/comment/:id' => 'post#comment'

  delete 'post/delete/:id' => 'post#delete'
end

board/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

board/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :model
  belongs_to :post
end

board/app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, :dependent => :destroy
  has_many :comments
  paginates_per 10

end

board/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :model
  has_many :comments
end

board/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

board/app/controllers/post_controller.rb
class PostController < ApplicationController

  def index

   @post =  Post.page params[:page]

  end
  def post
    @post = Post.new
    @post.model_id = current_model.id
    @post.title = params[:title]
    @post.content = params[:content]
    @post.save


    redirect_to '/'

  end
  def comment
    @post = Post.find(params[:id])
    @post.comments.create(content: params[:input_comment], model_id: current_model.id)

    redirect_to '/post/edit/'+ params[:id]

  end
  def edit
    @post = Post.find(params[:id])

  end
  def update
    @post = Post.find(params[:id])
    @post.title = params[:title]
    @post.content = params[:content]
    @post.save

    redirect_to '/'
  end
  def delete
    Post.find(params[:id]).destroy

    redirect_to '/'

  end
end

board/app/helpers/application_helper.rb
module ApplicationHelper
end

board/app/helpers/post_helper.rb
module PostHelper
end

board/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Board</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

board/app/views/post/edit.html.erb
<h1>수정하는 페이지</h1>

<form action="/post/update/<%= @post.id %>" method="get">
<table>
  <ul>
      <tr>
        <td>제목 : <input type="text" name="title" value="<%= @post.title %>"></td>
        <td>내용 : <textarea name="content" value="<%= @post.content %>"></textarea></td>
      </tr>
  </ul>
</table>
  <input type="submit" value="수정하기">
</form>

<a href="/post/delete/<%= @post.id %>" data-method="delete">삭제하기</a>

<form action="/post/comment/<%= @post.id %>">
  <table>
    <tr>
      <td>댓글 : <input type="text" name="input_comment"></td>
    </tr>
  </table>
  <input type="submit" value="댓글등록">
</form>

  <table>
  <ul>
        <% @post.comments.each do |i| %>
          <td> <%= i.content %></td>
        <% end %>
  </ul>
</table>

board/app/views/post/index.html.erb
<% if model_signed_in? %>
  <%= link_to '로 그 아 웃' , '/models/sign_out', method: :delete %>
<% else %>
  <a href ="/models/sign_in"> 로그인</a>
  <a href="/models/sign_up">회원가입</a>
<% end%>


<form action="/post/post" method="get">
  제목 : <input type="text" name="title">
  내용 : <textarea name="content"></textarea>
  <input type="submit" value="글쓰기">
</form>


<table>
  <ul>
    <% @post.reverse.each do |i| %>
      <tr>
        <td>제목 :<a href="post/edit/<%=i.id%>"><%= i.title %></a></td>
      </tr>
    <% end %>
  </ul>
</table>

<% paginate @post %>